title: QMK Configurator
email: hello@qmk.fm
show_downloads: true
description: An open source firmware for AVR and ARM based keyboards
baseurl: ""
url: "http://config.qmk.fm"
github_username: qmk
repository: qmk/qmk_configurator
theme: jekyll-theme-minimal